# Generated by Django 3.1.6 on 2021-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210203_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
